### PR TITLE
Units & Camera Bugfix

### LINKED ISSUE #41: Bugfix: Unit Errors
Fix the following bugs concerning Units:

- Units are no longer displayed on the client.
- Units, if placed outside the board, cause a server crash.

### PR DESCRIPTION
**Pull request by kjniemela**
closes #41 & #43

- Fixed units not displaying correctly.
- Fixed server crashing when units spawned outside the map.
- Fixed tile spacing.
- Eliminated magic numbers in the render functions.
- Fixed selector and clipping drift.

### CODE REVIEW

File: src/server/map.ts [hunk 1]
```diff
@@ -83,6 +83,10 @@ export class Map {
     this.tileUpdate(coords);
   }
 
+  isInBounds(coords: Coords): boolean {
+    return coords.x > 0 && coords.x < this.width && coords.y > 0 && coords.y < this.height;
```
Comment (JoelNiemela) [inline src/server/map.ts:87]: Aren't x = 0 and y = 0 valid coords?
So, shouldn't this read `return coords.x >= 0 && coords.x < this.width && coords.y >= 0 && coords.y < this.height;` instead?
