### PR TITLE
Server Connect Fixes

### LINKED ISSUE #73: Bugfix [SEVERE]: Empty Server IP
When the server IP stored in local storage is set to the empty string, the game will enter a broken state from which it can not be recovered without resetting the server IP manually through the console. This is likely due to an uncaught error generated by attempting to connect to `wss://`, which is not a legal URL.

### LINKED ISSUE #74: Bugfix: Cannot switch servers over ws protocol.
If the user attempts to connect to a `ws://` (non-secure, non-default but supported protocol) server through the `Switch Server` menu, the menu will not close properly until the page is reloaded, even if the connection was successful.

### PR DESCRIPTION
**Pull request by kjniemela**
closes #73; closes #74 

- Fixed game crashing if IP is empty string.
- Added reload error message on fatal error (should never be seen hopefully).
- Fixed Switch Server menu staying open.

### CODE REVIEW

File: src/client/widgets.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ class TextAlert {
     this.element.appendChild(this.messageElement);
 
     this.submitBtn = document.createElement('button');
-    this.submitBtn.innerText = 'Ok';
+    this.submitBtn.innerText = options.submitText || 'Ok';
```
Comment (JoelNiemela) [inline src/client/widgets.ts:65]: Maybe `options.submitText ?? 'Ok'` might be clearer.

**Review by JoelNiemela — APPROVED** [review]
